"""Initial RAG schema: rag_documents, rag_chunks, rag_ingestion_jobs

Revision ID: 0001
Revises:
Create Date: 2026-09-14 09:00:00.000000

Notes
-----
- Requires the `vector` extension (created by docker/init.sql on first volume init).
- Embedding dimension is 256, matching Settings.embedding_dimension default.
  If you change the embedding provider dimension, generate a new migration;
  do NOT edit this file.
- HNSW index is intentionally omitted here.  Add it in a separate migration
  once the corpus is large enough to justify approximate search.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers
revision: str = "0001"
down_revision: str | None = None
branch_labels = None
depends_on = None

# Embedding dimension used at the time this migration was generated.
# Must stay in sync with Settings.embedding_dimension unless a follow-up
# migration explicitly alters the column.
_EMBEDDING_DIM = 256


def upgrade() -> None:
    # ------------------------------------------------------------------
    # Ensure the pgvector extension exists (idempotent).
    # docker/init.sql already creates it on a fresh volume; this guard
    # covers running migrations against an existing database that was
    # set up without the init script.
    # ------------------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ------------------------------------------------------------------
    # rag_documents
    # ------------------------------------------------------------------
    op.create_table(
        "rag_documents",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("workspace_id", sa.String(100), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("source_type", sa.String(50), nullable=False),
        sa.Column("source_id", sa.String(200), nullable=True),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column("metadata", sa.JSON, nullable=False, server_default="{}"),
        sa.Column(
            "status",
            sa.String(20),
            nullable=False,
            server_default="active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.create_index(
        "ix_rag_documents_workspace_id",
        "rag_documents",
        ["workspace_id"],
    )
    op.create_index(
        "ix_rag_documents_workspace_source",
        "rag_documents",
        ["workspace_id", "source_type", "source_id"],
    )

    # ------------------------------------------------------------------
    # rag_chunks
    # ------------------------------------------------------------------
    op.create_table(
        "rag_chunks",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column(
            "document_id",
            sa.String(64),
            sa.ForeignKey("rag_documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.String(100), nullable=False),
        sa.Column("ordinal", sa.Integer, nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("token_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("metadata", sa.JSON, nullable=False, server_default="{}"),
        sa.Column("embedding", Vector(_EMBEDDING_DIM), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_rag_chunks_doc_ordinal"),
    )
    op.create_index(
        "ix_rag_chunks_document_id",
        "rag_chunks",
        ["document_id"],
    )
    op.create_index(
        "ix_rag_chunks_workspace_id",
        "rag_chunks",
        ["workspace_id"],
    )
    op.create_index(
        "ix_rag_chunks_workspace_document",
        "rag_chunks",
        ["workspace_id", "document_id"],
    )

    # ------------------------------------------------------------------
    # rag_ingestion_jobs
    # ------------------------------------------------------------------
    op.create_table(
        "rag_ingestion_jobs",
        sa.Column("id", sa.String(64), primary_key=True),
        sa.Column("workspace_id", sa.String(100), nullable=False),
        sa.Column(
            "document_id",
            sa.String(64),
            sa.ForeignKey("rag_documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(20),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("attempts", sa.Integer, nullable=False, server_default="0"),
        sa.Column("error", sa.Text, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.create_index(
        "ix_rag_ingestion_jobs_workspace_id",
        "rag_ingestion_jobs",
        ["workspace_id"],
    )
    op.create_index(
        "ix_rag_ingestion_jobs_document_id",
        "rag_ingestion_jobs",
        ["document_id"],
    )
    op.create_index(
        "ix_rag_ingestion_jobs_status",
        "rag_ingestion_jobs",
        ["status"],
    )


def downgrade() -> None:
    op.drop_table("rag_ingestion_jobs")
    op.drop_table("rag_chunks")
    op.drop_table("rag_documents")
